// Code generated by Kitex v0.16.3. DO NOT EDIT.

package agentplatformservice

import (
	"context"
	"errors"
	agentplatform "github.com/S-zhi/ThirdBrain/agent-platform/kitex_gen/agentplatform"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ExecuteKnowledgeAssist": kitex.NewMethodInfo(
		executeKnowledgeAssistHandler,
		newAgentPlatformServiceExecuteKnowledgeAssistArgs,
		newAgentPlatformServiceExecuteKnowledgeAssistResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	agentPlatformServiceServiceInfo                = NewServiceInfo()
	agentPlatformServiceServiceInfoForClient       = NewServiceInfoForClient()
	agentPlatformServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return agentPlatformServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return agentPlatformServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return agentPlatformServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AgentPlatformService"
	handlerType := (*agentplatform.AgentPlatformService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "agentplatform",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func executeKnowledgeAssistHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agentplatform.AgentPlatformServiceExecuteKnowledgeAssistArgs)
	realResult := result.(*agentplatform.AgentPlatformServiceExecuteKnowledgeAssistResult)
	success, err := handler.(agentplatform.AgentPlatformService).ExecuteKnowledgeAssist(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentPlatformServiceExecuteKnowledgeAssistArgs() interface{} {
	return agentplatform.NewAgentPlatformServiceExecuteKnowledgeAssistArgs()
}

func newAgentPlatformServiceExecuteKnowledgeAssistResult() interface{} {
	return agentplatform.NewAgentPlatformServiceExecuteKnowledgeAssistResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ExecuteKnowledgeAssist(ctx context.Context, request *agentplatform.ExecuteKnowledgeAssistRequest) (r *agentplatform.ExecuteKnowledgeAssistResponse, err error) {
	var _args agentplatform.AgentPlatformServiceExecuteKnowledgeAssistArgs
	_args.Request = request
	var _result agentplatform.AgentPlatformServiceExecuteKnowledgeAssistResult
	if err = p.c.Call(ctx, "ExecuteKnowledgeAssist", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
