// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package agentplatform

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type AssistStatus int64

const (
	AssistStatus_COMPLETED AssistStatus = 1
	AssistStatus_ABSTAINED AssistStatus = 2
	AssistStatus_FAILED    AssistStatus = 3
)

func (p AssistStatus) String() string {
	switch p {
	case AssistStatus_COMPLETED:
		return "COMPLETED"
	case AssistStatus_ABSTAINED:
		return "ABSTAINED"
	case AssistStatus_FAILED:
		return "FAILED"
	}
	return "<UNSET>"
}

func AssistStatusFromString(s string) (AssistStatus, error) {
	switch s {
	case "COMPLETED":
		return AssistStatus_COMPLETED, nil
	case "ABSTAINED":
		return AssistStatus_ABSTAINED, nil
	case "FAILED":
		return AssistStatus_FAILED, nil
	}
	return AssistStatus(0), fmt.Errorf("not a valid AssistStatus string")
}

func AssistStatusPtr(v AssistStatus) *AssistStatus { return &v }
func (p *AssistStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = AssistStatus(result.Int64)
	return
}

func (p *AssistStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RetrievalScope struct {
	WikiId           string   `thrift:"wiki_id,1" frugal:"1,default,string" json:"wiki_id"`
	Namespace        string   `thrift:"namespace,2" frugal:"2,default,string" json:"namespace"`
	Version          string   `thrift:"version,3" frugal:"3,default,string" json:"version"`
	Language         *string  `thrift:"language,4,optional" frugal:"4,optional,string" json:"language,omitempty"`
	RagCollectionIds []string `thrift:"rag_collection_ids,5,optional" frugal:"5,optional,list<string>" json:"rag_collection_ids,omitempty"`
}

func NewRetrievalScope() *RetrievalScope {
	return &RetrievalScope{}
}

func (p *RetrievalScope) InitDefault() {
}

func (p *RetrievalScope) GetWikiId() (v string) {
	return p.WikiId
}

func (p *RetrievalScope) GetNamespace() (v string) {
	return p.Namespace
}

func (p *RetrievalScope) GetVersion() (v string) {
	return p.Version
}

var RetrievalScope_Language_DEFAULT string

func (p *RetrievalScope) GetLanguage() (v string) {
	if !p.IsSetLanguage() {
		return RetrievalScope_Language_DEFAULT
	}
	return *p.Language
}

var RetrievalScope_RagCollectionIds_DEFAULT []string

func (p *RetrievalScope) GetRagCollectionIds() (v []string) {
	if !p.IsSetRagCollectionIds() {
		return RetrievalScope_RagCollectionIds_DEFAULT
	}
	return p.RagCollectionIds
}
func (p *RetrievalScope) SetWikiId(val string) {
	p.WikiId = val
}
func (p *RetrievalScope) SetNamespace(val string) {
	p.Namespace = val
}
func (p *RetrievalScope) SetVersion(val string) {
	p.Version = val
}
func (p *RetrievalScope) SetLanguage(val *string) {
	p.Language = val
}
func (p *RetrievalScope) SetRagCollectionIds(val []string) {
	p.RagCollectionIds = val
}

func (p *RetrievalScope) IsSetLanguage() bool {
	return p.Language != nil
}

func (p *RetrievalScope) IsSetRagCollectionIds() bool {
	return p.RagCollectionIds != nil
}

func (p *RetrievalScope) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RetrievalScope(%+v)", *p)
}

var fieldIDToName_RetrievalScope = map[int16]string{
	1: "wiki_id",
	2: "namespace",
	3: "version",
	4: "language",
	5: "rag_collection_ids",
}

type AssistPolicy struct {
	DeadlineMs   *int32 `thrift:"deadline_ms,1,optional" frugal:"1,optional,i32" json:"deadline_ms,omitempty"`
	MaxToolCalls *int16 `thrift:"max_tool_calls,2,optional" frugal:"2,optional,i16" json:"max_tool_calls,omitempty"`
}

func NewAssistPolicy() *AssistPolicy {
	return &AssistPolicy{}
}

func (p *AssistPolicy) InitDefault() {
}

var AssistPolicy_DeadlineMs_DEFAULT int32

func (p *AssistPolicy) GetDeadlineMs() (v int32) {
	if !p.IsSetDeadlineMs() {
		return AssistPolicy_DeadlineMs_DEFAULT
	}
	return *p.DeadlineMs
}

var AssistPolicy_MaxToolCalls_DEFAULT int16

func (p *AssistPolicy) GetMaxToolCalls() (v int16) {
	if !p.IsSetMaxToolCalls() {
		return AssistPolicy_MaxToolCalls_DEFAULT
	}
	return *p.MaxToolCalls
}
func (p *AssistPolicy) SetDeadlineMs(val *int32) {
	p.DeadlineMs = val
}
func (p *AssistPolicy) SetMaxToolCalls(val *int16) {
	p.MaxToolCalls = val
}

func (p *AssistPolicy) IsSetDeadlineMs() bool {
	return p.DeadlineMs != nil
}

func (p *AssistPolicy) IsSetMaxToolCalls() bool {
	return p.MaxToolCalls != nil
}

func (p *AssistPolicy) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AssistPolicy(%+v)", *p)
}

var fieldIDToName_AssistPolicy = map[int16]string{
	1: "deadline_ms",
	2: "max_tool_calls",
}

type ExecuteKnowledgeAssistRequest struct {
	RequestId     string          `thrift:"request_id,1" frugal:"1,default,string" json:"request_id"`
	Query         string          `thrift:"query,2" frugal:"2,default,string" json:"query"`
	Scope         *RetrievalScope `thrift:"scope,3" frugal:"3,default,RetrievalScope" json:"scope"`
	Policy        *AssistPolicy   `thrift:"policy,4,optional" frugal:"4,optional,AssistPolicy" json:"policy,omitempty"`
	CorrelationId *string         `thrift:"correlation_id,5,optional" frugal:"5,optional,string" json:"correlation_id,omitempty"`
}

func NewExecuteKnowledgeAssistRequest() *ExecuteKnowledgeAssistRequest {
	return &ExecuteKnowledgeAssistRequest{}
}

func (p *ExecuteKnowledgeAssistRequest) InitDefault() {
}

func (p *ExecuteKnowledgeAssistRequest) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ExecuteKnowledgeAssistRequest) GetQuery() (v string) {
	return p.Query
}

var ExecuteKnowledgeAssistRequest_Scope_DEFAULT *RetrievalScope

func (p *ExecuteKnowledgeAssistRequest) GetScope() (v *RetrievalScope) {
	if !p.IsSetScope() {
		return ExecuteKnowledgeAssistRequest_Scope_DEFAULT
	}
	return p.Scope
}

var ExecuteKnowledgeAssistRequest_Policy_DEFAULT *AssistPolicy

func (p *ExecuteKnowledgeAssistRequest) GetPolicy() (v *AssistPolicy) {
	if !p.IsSetPolicy() {
		return ExecuteKnowledgeAssistRequest_Policy_DEFAULT
	}
	return p.Policy
}

var ExecuteKnowledgeAssistRequest_CorrelationId_DEFAULT string

func (p *ExecuteKnowledgeAssistRequest) GetCorrelationId() (v string) {
	if !p.IsSetCorrelationId() {
		return ExecuteKnowledgeAssistRequest_CorrelationId_DEFAULT
	}
	return *p.CorrelationId
}
func (p *ExecuteKnowledgeAssistRequest) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ExecuteKnowledgeAssistRequest) SetQuery(val string) {
	p.Query = val
}
func (p *ExecuteKnowledgeAssistRequest) SetScope(val *RetrievalScope) {
	p.Scope = val
}
func (p *ExecuteKnowledgeAssistRequest) SetPolicy(val *AssistPolicy) {
	p.Policy = val
}
func (p *ExecuteKnowledgeAssistRequest) SetCorrelationId(val *string) {
	p.CorrelationId = val
}

func (p *ExecuteKnowledgeAssistRequest) IsSetScope() bool {
	return p.Scope != nil
}

func (p *ExecuteKnowledgeAssistRequest) IsSetPolicy() bool {
	return p.Policy != nil
}

func (p *ExecuteKnowledgeAssistRequest) IsSetCorrelationId() bool {
	return p.CorrelationId != nil
}

func (p *ExecuteKnowledgeAssistRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExecuteKnowledgeAssistRequest(%+v)", *p)
}

var fieldIDToName_ExecuteKnowledgeAssistRequest = map[int16]string{
	1: "request_id",
	2: "query",
	3: "scope",
	4: "policy",
	5: "correlation_id",
}

type AgentTraceEvent struct {
	Stage  string `thrift:"stage,1" frugal:"1,default,string" json:"stage"`
	Detail string `thrift:"detail,2" frugal:"2,default,string" json:"detail"`
}

func NewAgentTraceEvent() *AgentTraceEvent {
	return &AgentTraceEvent{}
}

func (p *AgentTraceEvent) InitDefault() {
}

func (p *AgentTraceEvent) GetStage() (v string) {
	return p.Stage
}

func (p *AgentTraceEvent) GetDetail() (v string) {
	return p.Detail
}
func (p *AgentTraceEvent) SetStage(val string) {
	p.Stage = val
}
func (p *AgentTraceEvent) SetDetail(val string) {
	p.Detail = val
}

func (p *AgentTraceEvent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentTraceEvent(%+v)", *p)
}

var fieldIDToName_AgentTraceEvent = map[int16]string{
	1: "stage",
	2: "detail",
}

type ExecuteKnowledgeAssistResponse struct {
	RequestId     string             `thrift:"request_id,1" frugal:"1,default,string" json:"request_id"`
	Status        AssistStatus       `thrift:"status,2" frugal:"2,default,AssistStatus" json:"status"`
	ContextPacket *string            `thrift:"context_packet,3,optional" frugal:"3,optional,string" json:"context_packet,omitempty"`
	Warnings      []string           `thrift:"warnings,4,optional" frugal:"4,optional,list<string>" json:"warnings,omitempty"`
	Trace         []*AgentTraceEvent `thrift:"trace,5,optional" frugal:"5,optional,list<AgentTraceEvent>" json:"trace,omitempty"`
	ErrorCode     *string            `thrift:"error_code,6,optional" frugal:"6,optional,string" json:"error_code,omitempty"`
	ErrorMessage  *string            `thrift:"error_message,7,optional" frugal:"7,optional,string" json:"error_message,omitempty"`
}

func NewExecuteKnowledgeAssistResponse() *ExecuteKnowledgeAssistResponse {
	return &ExecuteKnowledgeAssistResponse{}
}

func (p *ExecuteKnowledgeAssistResponse) InitDefault() {
}

func (p *ExecuteKnowledgeAssistResponse) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ExecuteKnowledgeAssistResponse) GetStatus() (v AssistStatus) {
	return p.Status
}

var ExecuteKnowledgeAssistResponse_ContextPacket_DEFAULT string

func (p *ExecuteKnowledgeAssistResponse) GetContextPacket() (v string) {
	if !p.IsSetContextPacket() {
		return ExecuteKnowledgeAssistResponse_ContextPacket_DEFAULT
	}
	return *p.ContextPacket
}

var ExecuteKnowledgeAssistResponse_Warnings_DEFAULT []string

func (p *ExecuteKnowledgeAssistResponse) GetWarnings() (v []string) {
	if !p.IsSetWarnings() {
		return ExecuteKnowledgeAssistResponse_Warnings_DEFAULT
	}
	return p.Warnings
}

var ExecuteKnowledgeAssistResponse_Trace_DEFAULT []*AgentTraceEvent

func (p *ExecuteKnowledgeAssistResponse) GetTrace() (v []*AgentTraceEvent) {
	if !p.IsSetTrace() {
		return ExecuteKnowledgeAssistResponse_Trace_DEFAULT
	}
	return p.Trace
}

var ExecuteKnowledgeAssistResponse_ErrorCode_DEFAULT string

func (p *ExecuteKnowledgeAssistResponse) GetErrorCode() (v string) {
	if !p.IsSetErrorCode() {
		return ExecuteKnowledgeAssistResponse_ErrorCode_DEFAULT
	}
	return *p.ErrorCode
}

var ExecuteKnowledgeAssistResponse_ErrorMessage_DEFAULT string

func (p *ExecuteKnowledgeAssistResponse) GetErrorMessage() (v string) {
	if !p.IsSetErrorMessage() {
		return ExecuteKnowledgeAssistResponse_ErrorMessage_DEFAULT
	}
	return *p.ErrorMessage
}
func (p *ExecuteKnowledgeAssistResponse) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ExecuteKnowledgeAssistResponse) SetStatus(val AssistStatus) {
	p.Status = val
}
func (p *ExecuteKnowledgeAssistResponse) SetContextPacket(val *string) {
	p.ContextPacket = val
}
func (p *ExecuteKnowledgeAssistResponse) SetWarnings(val []string) {
	p.Warnings = val
}
func (p *ExecuteKnowledgeAssistResponse) SetTrace(val []*AgentTraceEvent) {
	p.Trace = val
}
func (p *ExecuteKnowledgeAssistResponse) SetErrorCode(val *string) {
	p.ErrorCode = val
}
func (p *ExecuteKnowledgeAssistResponse) SetErrorMessage(val *string) {
	p.ErrorMessage = val
}

func (p *ExecuteKnowledgeAssistResponse) IsSetContextPacket() bool {
	return p.ContextPacket != nil
}

func (p *ExecuteKnowledgeAssistResponse) IsSetWarnings() bool {
	return p.Warnings != nil
}

func (p *ExecuteKnowledgeAssistResponse) IsSetTrace() bool {
	return p.Trace != nil
}

func (p *ExecuteKnowledgeAssistResponse) IsSetErrorCode() bool {
	return p.ErrorCode != nil
}

func (p *ExecuteKnowledgeAssistResponse) IsSetErrorMessage() bool {
	return p.ErrorMessage != nil
}

func (p *ExecuteKnowledgeAssistResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExecuteKnowledgeAssistResponse(%+v)", *p)
}

var fieldIDToName_ExecuteKnowledgeAssistResponse = map[int16]string{
	1: "request_id",
	2: "status",
	3: "context_packet",
	4: "warnings",
	5: "trace",
	6: "error_code",
	7: "error_message",
}

type AgentPlatformService interface {
	ExecuteKnowledgeAssist(ctx context.Context, request *ExecuteKnowledgeAssistRequest) (r *ExecuteKnowledgeAssistResponse, err error)
}

type AgentPlatformServiceExecuteKnowledgeAssistArgs struct {
	Request *ExecuteKnowledgeAssistRequest `thrift:"request,1" frugal:"1,default,ExecuteKnowledgeAssistRequest" json:"request"`
}

func NewAgentPlatformServiceExecuteKnowledgeAssistArgs() *AgentPlatformServiceExecuteKnowledgeAssistArgs {
	return &AgentPlatformServiceExecuteKnowledgeAssistArgs{}
}

func (p *AgentPlatformServiceExecuteKnowledgeAssistArgs) InitDefault() {
}

var AgentPlatformServiceExecuteKnowledgeAssistArgs_Request_DEFAULT *ExecuteKnowledgeAssistRequest

func (p *AgentPlatformServiceExecuteKnowledgeAssistArgs) GetRequest() (v *ExecuteKnowledgeAssistRequest) {
	if !p.IsSetRequest() {
		return AgentPlatformServiceExecuteKnowledgeAssistArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AgentPlatformServiceExecuteKnowledgeAssistArgs) SetRequest(val *ExecuteKnowledgeAssistRequest) {
	p.Request = val
}

func (p *AgentPlatformServiceExecuteKnowledgeAssistArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AgentPlatformServiceExecuteKnowledgeAssistArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentPlatformServiceExecuteKnowledgeAssistArgs(%+v)", *p)
}

var fieldIDToName_AgentPlatformServiceExecuteKnowledgeAssistArgs = map[int16]string{
	1: "request",
}

type AgentPlatformServiceExecuteKnowledgeAssistResult struct {
	Success *ExecuteKnowledgeAssistResponse `thrift:"success,0,optional" frugal:"0,optional,ExecuteKnowledgeAssistResponse" json:"success,omitempty"`
}

func NewAgentPlatformServiceExecuteKnowledgeAssistResult() *AgentPlatformServiceExecuteKnowledgeAssistResult {
	return &AgentPlatformServiceExecuteKnowledgeAssistResult{}
}

func (p *AgentPlatformServiceExecuteKnowledgeAssistResult) InitDefault() {
}

var AgentPlatformServiceExecuteKnowledgeAssistResult_Success_DEFAULT *ExecuteKnowledgeAssistResponse

func (p *AgentPlatformServiceExecuteKnowledgeAssistResult) GetSuccess() (v *ExecuteKnowledgeAssistResponse) {
	if !p.IsSetSuccess() {
		return AgentPlatformServiceExecuteKnowledgeAssistResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AgentPlatformServiceExecuteKnowledgeAssistResult) SetSuccess(x interface{}) {
	p.Success = x.(*ExecuteKnowledgeAssistResponse)
}

func (p *AgentPlatformServiceExecuteKnowledgeAssistResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AgentPlatformServiceExecuteKnowledgeAssistResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentPlatformServiceExecuteKnowledgeAssistResult(%+v)", *p)
}

var fieldIDToName_AgentPlatformServiceExecuteKnowledgeAssistResult = map[int16]string{
	0: "success",
}
