"""LLM Knowledge Wiki 的写入面与只读查询面。"""

from src.knowledge.contracts import KnowledgeExtractor, KnowledgeIndexWriter, KnowledgeRepository
from src.knowledge.models import (
    ActiveArtifact,
    ArtifactDraft,
    ArtifactStatus,
    ArtifactType,
    Confidence,
    EvidenceRef,
    ExtractionResult,
    KnowledgeDocumentInput,
    RagCollectionInput,
    RelationType,
    SourcePart,
    UpdateOptions,
    UpdateResult,
    WikiUpdateInput,
)
from src.knowledge.openai_extractor import OpenAIKnowledgeExtractor
from src.knowledge.query_contracts import (
    Abstention,
    BudgetUsage,
    CacheMiss,
    EnrichmentRequest,
    FollowUpAction,
    KnowledgeItem,
    MatchConfidence,
    QueryBudget,
    QueryEvidenceRef,
    QueryKnowledgeOptions,
    QueryKnowledgeResult,
    QueryScope,
    RankedKnowledgeItem,
    ReaderSearchResult,
    RecallCapsule,
    RecallCapsuleItem,
    RelationRef,
    RetrievalChannel,
    RetrievalHit,
    StrategyReport,
    TraceStage,
)
from src.knowledge.service import KnowledgeUpdateService
from src.knowledge.zvec_index import ZvecKnowledgeIndexWriter

# 查询面与写入面使用同一 ArtifactType，保留旧查询名称作为兼容别名。
ArtifactKind = ArtifactType

__all__ = [
    "Abstention",
    "ActiveArtifact",
    "ArtifactDraft",
    "ArtifactKind",
    "ArtifactStatus",
    "ArtifactType",
    "BudgetUsage",
    "CacheMiss",
    "Confidence",
    "EnrichmentRequest",
    "EvidenceRef",
    "ExtractionResult",
    "FollowUpAction",
    "KnowledgeDocumentInput",
    "KnowledgeExtractor",
    "KnowledgeIndexWriter",
    "KnowledgeItem",
    "KnowledgeRepository",
    "KnowledgeUpdateService",
    "MatchConfidence",
    "OpenAIKnowledgeExtractor",
    "QueryBudget",
    "QueryEvidenceRef",
    "QueryKnowledgeOptions",
    "QueryKnowledgeResult",
    "QueryScope",
    "RagCollectionInput",
    "RankedKnowledgeItem",
    "ReaderSearchResult",
    "RecallCapsule",
    "RecallCapsuleItem",
    "RelationRef",
    "RelationType",
    "RetrievalChannel",
    "RetrievalHit",
    "SourcePart",
    "StrategyReport",
    "TraceStage",
    "UpdateOptions",
    "UpdateResult",
    "WikiUpdateInput",
    "ZvecKnowledgeIndexWriter",
]
